name: FoodWaste Ingestion Pipeline CI/CD

# 1. GATILHOS: Quando a esteira roda sozinha
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Agendador de tempo (Cron Job): Toda segunda-feira às 09:00 de Brasília (12:00 UTC)
  schedule:
    - cron: '0 12 * * 1'

jobs:
  # JOB 1: Validar a qualidade e sintaxe do código Python
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        if [ -f src/ingestao/requirements.txt ]; then pip install -r src/ingestao/requirements.txt; fi


  # JOB 2: Simular o Build do Docker para garantir que a imagem está saudável
  docker-build-test:
    needs: lint-and-test # Só roda se o teste de cima passar!
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    # MÁGICA: Pega o bloco de texto do cofre e cria o arquivo .env pro Docker usar
    - name: Criar arquivo .env a partir do GitHub Secrets
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Tenta buildar a imagem usando o seu Dockerfile
    - name: Testar Build da Imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        file: src/ingestao/Dockerfile
        push: false # Mantenha false até decidir enviar a imagem para o Docker Hub ou AWS ECR